language: node_js
node_js:
  - "8.6"
env:
  - MYSQL_HOST=127.0.0.1
  - MYSQL_USER=root
  - MYSQL_PASSWORD=
  - MYSQL_DATABASE_TEST=categoria_teste
  - CRYPTO_KEY=b7e94be5
  - JWT_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE categoria_teste;'
  - mysql -e 'use categoria_teste;'
  - mysql -e 'USE categoria_teste; CREATE TABLE categorias (id int(11) NOT NULL AUTO_INCREMENT,name varchar(255) DEFAULT NULL, PRIMARY KEY (id));'
  - mysql -e 'USE categoria_teste; CREATE TABLE usuarios (id int(11) NOT NULL AUTO_INCREMENT,email varchar(255) DEFAULT NULL,password varchar(255) DEFAULT NULL,PRIMARY KEY (id));'
script:
  - npm test